version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:15.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:15.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: install aws cli
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: build project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "build successful"
      - run:
          name: deploy to aws s3
          command: |
            if [ "${CURRENT_BRANCH}" == "main" ]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PRD} --delete
            elif [ "${CURRENT_BRANCH}" == "stg" ]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STG} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
            fi

  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/node:15.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: install aws cli
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: build project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r *.[^.]*
            echo "build successful"
      - run:
          name: deploy to aws s3
          command: |
            aws configure set preview.cloudfront
            if [ "${CURRENT_BRANCH}" == "main" ]
            then
              aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID_PRD} --paths /\*
            elif [ "${CURRENT_BRANCH}" == "stg" ]
            then
              aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID_STG} --paths /\*
            else
              aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID_DEV} --paths /\*
            fi

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - stg
                - main
      - deploy-to-aws-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - dev
                - stg
                - main
